---
MODEL:
  DATA_DIM: 162 # 180
  CS_DIM: 40
  SEQ_LEN: 180
  FP_LEN: 40
  IC_ENC_DIM: 100
  CI_ENC_DIM: 80
  CON_DIM: 80
  CO_DIM: 4
  IC_DIM: 100
  GEN_DIM: 100
  FAC_DIM: 40
  DROPOUT_RATE: 0.05 # OVERWRITTEN
  CD_RATE: 0.5 # OVERWRITTEN
  CD_PASS_RATE: 0.0
  CO_PRIOR_TAU: 10.0
  CO_PRIOR_NVAR: 0.1
  IC_PRIOR_VAR: 0.1
  IC_POST_VAR_MIN: 1.0e-4
TRAIN:
  DATA:
    DIR: data/
    PREFIX: mc_maze_large_
  PATIENCE: 5000 # Early stopping should be off
  BATCH_SIZE: 100 # 100 for the 230-sample dataset
  MAX_EPOCHS: 10000
  MAX_GRAD_NORM: 200.0
  LOSS_SCALE: 10000.0
  LR: 
    INIT: 0.004 # OVERWRITTEN
    STOP: 1.0e-10
    DECAY: 1.0
    PATIENCE: 0
  ADAM_EPSILON: 1.0e-8
  L2:
    START_EPOCH: 0
    INCREASE_EPOCH: 80
    IC_ENC_SCALE: 0.0 # UNUSED
    CI_ENC_SCALE: 0.0 # UNUSED
    GEN_SCALE: 1.0e-4 # OVERWRITTEN
    CON_SCALE: 1.0e-4 # OVERWRITTEN
  KL:
    START_EPOCH: 0
    INCREASE_EPOCH: 80
    IC_WEIGHT: 1.0e-4 # OVERWRITTEN
    CO_WEIGHT:  1.0e-4 # OVERWRITTEN
  PBT_MODE: True
  TUNE_MODE: True
  LOG_HPS: True
  USE_TB: False
  MODEL_DIR: '' # OVERWRITTEN
  OVERWRITE: True
